site_name: Non-Tech Notes
site_description: Personal non-technical notes
site_author: marco v
repo_url: https://github.com/marcov/non-tech-notes
site_url: https://notes.sba.lat
docs_dir: docs

#theme: readthedocs
theme: alabaster

#pages:
#- Home:
#  - Overview: 'README.md'
#  - ACME Documentation: 'ACME.md'
#- Installation:
#  - ACME Installation: 'installation/ACME.md'
#- Configuration:
#  - ACME Configuration: 'configuration/ACME.md'
#- Development:
#  - ACME Coding Conventions: 'development/ACME.md'
#- References: 'references.md'
#
#google_analytics: ['UA-#########-#', 'docs.sba.lat']
